# escape characters
@strftime = (
	"c locale date & time",
	"- - - -",
	"d day of the month (01-31)",
	"e day of the month (1-31)",
	"j day of the year (001-366)",
	"- - - -",
	"a short weekday name", 
	"A full weekday name",
	"u day of the week (1-7)",
	"w day of the week (0-6)",
	"W week number (00-53)",
	"V week number (01-53)",    
	"- - - -",	
	"b short month name",
	"B full month name",
	"m month (01-12)",
	"- - - -",
	"y year (2-digit 00-99)",
	"Y year (4-digit)",
	"C century (year/100)",
	"- - - -",	
	"H hour (00-23)",
	"k hour (0-23)",
	"I hour (01-12)",
	"l hour (1-12)",	
	"- - - -",
	"M minute (00-59)",
	"S second (00-59)",
	"- - - -",
	"p AM/PM",
	"P am/pm",
	"% %",
	);

@hylaserv = (
	"d destination phone number",
	"l LocalIdentifier or canonicalized FAXNumber",	
	"n canonicalized FAXNumber",
	"i job identifier",
	"- - - -",
	"m sender's electronic mail address",
	"s sender's name",
	"- - - -",
	"p current page number of session",
	"P current page number of job",
	"t total pages in session",
	"T total pages in job",
	);