@jobcodes=(
"J;j;JID;-5;Job identifier",
"J;Y;DateTime;-19;Scheduled date and time",    
"J;a;Status;1;Job state (one-character symbol)",
"J;o;owner;15;Fax owner", 
"J;c;client;20;Client machine name",
"J;S;Sender;30;Sender’s identity",
"J;M;mailaddr;30;Notification e-mail address",
"J;e;Number;-15.15;Public (external) format of dialstring",
"J;R;Receiver;30;Destination person (receiver)",
"J;P;Pages;5;# pages transmitted/total # pages to transmit",
"J;D;Dials;5;Total # dials/maximum # dials",
"J;T;Tries;5;Total # tries/maximum # tries",
"J;i;priority;5;Current scheduling priority",
"J;m;modem;5;Assigned modem",
"J;q;retry_time;6;Job retry time (MM::SS)",
"J;z;TTS;7;Time to send job (TTS)",
"J;s;Failure;.25;Job status information from last failure",
"R;o;owner;7;Fax owner", 
"R;t;Recvdate;-10;Compact representation of receive date/time",
"R;s;Sender;-25;Sender identity (TSI)",
"R;f;filename;-20;Document filename",
"R;n;Size;12;File size (bytes)",
"R;r;Res;5;Resolution of received data",
"R;p;Pages;5;Pages in document",
"R;h;timeSpent;8;Time spent receiving document",
"R;z;Status;1;A * if receive is going on",
"R;e;Failure;-40;Error description if an error occurred during receive",
);